In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

In [5]:
SPY_raw = pd.read_csv("../data/raw/SPY_raw.csv")
SPY_raw.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,SPY,SPY,SPY,SPY,SPY
1,Date,NaN,NaN,NaN,NaN,NaN
2,2015-01-02,169.26751708984375,170.4622791732047,168.23755844745486,170.05029571624917,121465900
3,2015-01-05,166.21055603027344,168.39406265503095,165.90569238867087,168.22927183721154,169632600
4,2015-01-06,164.64511108398438,167.03461063221943,163.85409714017257,166.51550733869482,209151400

In [6]:
list(SPY_raw.columns)

['Price', 'Close', 'High', 'Low', 'Open', 'Volume']

In [11]:
# Restructure the DataFrame
print(isinstance(SPY_raw.columns, pd.MultiIndex))

False

In [7]:
# inspect number of NaN values in each column
SPY_raw.isnull().sum()

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [12]:
SPY_raw.describe()

         Price               Close                High   Low  Open    Volume
count     2956                2955                2955  2955  2955      2955
unique    2956                2913                2953  2955  2955      2952
top     Ticker  173.41207885742188  184.49718062147466   SPY   SPY  89351900
freq         1                   2                   2     1     1         2